# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
cache: cocoapods
podfile: KFBlankSlateExample/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --repo-update --project-directory=KFBlankSlateExample
script:
- set -o pipefail && xcodebuild clean build -workspace KFBlankSlateExample/KFBlankSlateExample.xcworkspace -scheme KFBlankSlateExample -sdk iphonesimulator12.1 -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.1' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
